blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /api/blog

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
