# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        user_db:
            entity: { class: AppBundle\Entity\User }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_v1_doc:
            pattern:  ^/api/doc
            stateless: true
            anonymous: ~

        api_auth:
            pattern:  ^/api/auth
            stateless: true
            anonymous: ~

        create_user:
            pattern: ^/api/users$
            stateless: true
            methods: [POST]
            anonymous: ~

        change_password:
            pattern: ^/api/change_password/.*$
            stateless: true
            methods: [POST, GET]
            anonymous: ~

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticator:
                    - 'app.jwt_token_authenticator'

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
