<?php

namespace BlogBundle\Repository;

use BlogBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $title
     * @return Category|null
     */
    public function fetchOneByTitleLow($title)
    {


        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from('BlogBundle:Category', 'c')
            ->where('LOWER(c.title) LIKE LOWER(:title)')
            ->setParameter('title', $title)
            ->setMaxResults(1)
            ->getQuery();

        return ($query->getSingleResult());

    }

}
