auth:
    type:        rest
    resource:    AppBundle\Controller\AuthController

users:
    type:        rest
    resource:    AppBundle\Controller\UserController

change_password:
    path:     /change_password/{token}
    defaults: { _controller: AppBundle:Auth:changePassword }